config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    member do
      get :timeline
    end
  end
  
  get 'ranking', to: 'posts#ranking'
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :introduction, length: { maximum: 100 }
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_posts
    Post.where(user_id: self.following_ids + [self.id])
  end
  
  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end
  
  has_many :favorites
  has_many :likes, through: :favorites, source: :post
  
  def like(post)
    self.favorites.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end

  def liking?(post)
    self.likes.include?(post)
  end
  
  has_many :comments, dependent: :destroy
  
  mount_uploader :image, ImageUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25).search(params[:search])
    if logged_in?
      @posts = current_user.feed_posts.order(id: :desc).page(params[:page])
    else
      @post = Post.order(id: :desc).page(params[:page]).per(25)
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to controller: 'sessions', action: 'new'
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '更新しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page]).per(10)
    counts(@user)
  end
  
  def search
    @users = User.order(id: :desc).page(params[:page]).per(25).search(params[:search])
    if logged_in?
      @posts = current_user.feed_posts.order(id: :desc).page(params[:page])
    else
      @post = Post.order(id: :desc).page(params[:page]).per(25)
    end
    render :index
  end
  

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction, :image, :remove_image)
  end
  
  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user && logged_in?
      redirect_to root_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_items.html.erb
<ul class="nav nav-tabs nav-justified" id="user_items">
  <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">過去の投稿<h3><%= @count_posts %></h3></a></li>
  <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り<h3><%= @count_likes %></h3></a></li>
  <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー<h3><%= @count_followings %></h3></a></li>
  <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー<h3><%= @count_followers %></h3></a></li>
</ul>

app/views/users/_user_edit_button.html.erb
<div class="user-edit-button mt-3">
  <% if current_user == @user %>
    <%=link_to 'ユーザー情報編集', edit_user_path(@user) %>
  <% end %>
</div>

app/views/users/_user_image.html.erb
<div class="trim-image-to-circle m-0">
  <% if user.image? %>
    <%= image_tag user.image.url %>
  <% elsif %>
    <%= image_tag ('/no_user_image.png') %>
  <% end %>
</div>

app/views/users/_user_top.html.erb
<div class="user-left-image">
  <div class="trim-image-to-circle-lg m-0">
    <% if @user.image? %>
      <%= image_tag @user.image.url %>
    <% elsif %>
      <%= image_tag ('/no_user_image.png') %>
    <% end %>
  </div>
</div>
<div class="user-left-content">
  <h2><%= @user.name %></h2>
  <%= render 'relationships/follow_button', user: @user %>
  <p class="pt-1"><%= @user.introduction %></p>
  <%= render 'users/user_edit_button', user: @user %>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media p-2" id="user-<%= user.id %>">
        <%= render 'users/user_image', user: user %>
        <div class="media-body pl-2">
          <h5 class="mt-0"><%= user.name %></h5>
          <p class="mt-0"><%= user.introduction %></p>
          <div class="d-flex justify-content-between">
            <div class="d-flex justify-content-between">
              <p class="m-0"><small class="text-muted">記事数 <i class="fas fa-book-open fa-fw"></i> <%= user.posts.count %></small></p>
              <p class="m-0 ml-3"><small class="text-muted">フォロワー数 <i class="fas fa-users fa-fw"></i> <%= user.followers.count %></small></p>
            </div>
          </div>
          <div class="toppage-follow-button"><%= render 'relationships/follow_button', user: user %></div>
        </div>
      </li>
      <hr class="m-0">
    <% end %>
  </ul>
  <!--<%= paginate users, :param_name => 'user_page' %>-->
<% end %>

app/views/users/edit.html.erb
<div class="signup">
  <h1>ユーザー情報編集</h1>
  <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <%=f.label :image,"ユーザー画像" %>
    <div class="user-image">
      <div class="trim-image-to-circle-lg m-0">
        <img id="avatar_img_prev" src="#" class="hidden">
        <% if current_user.persisted? && current_user.image? %>
          <%= image_tag current_user.image.url, class: 'avatar_present_img' %>
        <% elsif %>
          <%= image_tag ('/no_user_image.png'), class: 'avatar_present_img' %>
        <% end %>
      </div>
      <div><%= f.file_field :image, id: 'post_img' %></div>
      <div><%= f.check_box :remove_image %>画像を削除する</div>
    </div>
    <div class="form-group">
      <%= f.label :name, 'ユーザーネーム' %>
      <%= f.text_field :name, placeholder: "ユーザーネームを入力(20文字以内)", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :introduction, '自己紹介' %>
      <%= f.text_area :introduction, placeholder: "自己紹介を入力(100文字以内)", class: 'form-control', rows: 5 %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'パスワード（確認用）' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="button-set">
      <%= link_to "キャンセル", :back, class: 'cancel-button'%>
      <%= f.submit '変更を保存', class: 'submit-button'%>
    </div>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="wrapper">
  <div class="user-left">
    <%= render 'users/user_top' %>
  </div>
  <div class="user-right">
    <%= render 'users/items'%>
    <% if @user.followers.count > 0  %>
      <%= render 'users', users: @followers %>
    <% else %>
      <p class="mt-3 pt-3 pb-3 no-followers">フォローされていません。</p>
    <% end %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="wrapper">
  <div class="user-left">
    <%= render 'users/user_top' %>
  </div>
  <div class="user-right">
    <%= render 'users/items'%>
    <% if @user.followings.count > 0  %>
      <%= render 'users', users: @followings %>
    <% else %>
      <p class="mt-3 pt-3 pb-3 no-followings">フォローしていません。</p>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="p-3 mt-3 mb-3">
      <%= form_tag(search_users_path, :method => 'get') do %>
        <div class="d-flex justify-content-center">
          <%= text_field_tag :search, '', class: 'user-search form-control', :placeholder => "ユーザー検索"%>
          <%= button_tag :type => "submit", :class =>"searth-btn btn btn-default btn-dark" do %>
            <i class="fa fa-search"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div>
      <% if @users.count > 0  %>
        <%= render 'users', users: @users %>
      <% else %>
        <p>該当するユーザーが見つかりませんでした。</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/likes.html.erb
<div class="wrapper">
  <div class="user-left">
    <%= render 'users/user_top' %>
  </div>
  <div class="user-right">
    <%= render 'users/items'%>
    <% if @user.likes.count > 0  %>
      <%= render 'posts/posts', posts: @likes %>
    <% else %>
      <p class="mt-3 pt-3 pb-3 no-likes">お気に入りはありません。</p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="signup">
  <h1>新規登録</h1>
  <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <%=f.label :image,"ユーザー画像（任意）" %>
    <div class="user-image">
      <div class="trim-image-to-circle-lg m-0">
        <img id="avatar_img_prev" src="#" class="hidden">
        <%= image_tag ('/no_user_image.png'), class: 'avatar_present_img' %>
      </div>
      <div><%= f.file_field :image, id: 'post_img' %></div>
      <div><%= f.check_box :remove_image %>画像を削除する</div>
    </div>
    <div class="form-group">
      <%= f.label :name, 'ユーザーネーム' %> <span class="badge badge-danger">必須</span>
      <%= f.text_field :name, placeholder: "ユーザーネームを入力(20文字以内)", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :introduction, '自己紹介（任意）' %>
      <%= f.text_area :introduction, placeholder: "自己紹介を入力(100文字以内)", class: 'form-control', rows: 5 %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %> <span class="badge badge-danger">必須</span>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password, 'パスワード' %> <span class="badge badge-danger">必須</span>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'パスワード（確認用）' %> <span class="badge badge-danger">必須</span>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="button-set">
      <%= link_to "キャンセル", :back, class: 'cancel-button'%>
      <%= f.submit '新規登録', class: 'submit-button' %>
    </div>
  <% end %>
</div>
 

app/views/users/show.html.erb
<div class="wrapper">
  <div class="user-left">
    <%= render 'users/user_top' %>
  </div>
  <div class="user-right">
    <%= render 'users/items'%>
    <% if @user.posts.count > 0  %>
      <%= render 'posts/posts', posts: @posts %>
    <% else %>
      <p class="mt-3 pt-3 pb-3 no-posts">投稿はありません。</p>
    <% end %>
  </div>
</div>