config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    member do
      get :timeline
    end
  end
  
  get 'ranking', to: 'posts#ranking'
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @posts_header = Post.includes(:user).order(id: :desc).limit(4)
    @users = User.includes(:posts).order(id: :desc).page(params[:user_page]).per(5)
    @posts = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
  end
end

app/views/toppages/index.html.erb
<ul class="list-unstyled m-0 mb-4" id="flex-container">
  <% @posts_header.each do |post| %>
    <li class="flex-container-item">
      <%= link_to post do %>
        <% if post.image? %>
          <%= image_tag post.image.url %>
        <% elsif %>
          <%= image_tag ('/no_post_image.png') %>
        <% end %>
      <% end %>
      <p class="flex-container-item-post-title"><%=link_to post.title, post %></p>
      <p class="flex-container-item-post-user"><%= post.user.name %></p>
      <div class="flex-container-item-post-item d-flex justify-content-between">
        <p class="m-0"><small><i class="fas fa-eye fa-fw"></i> <%= post.impressionist_count %></small></p>
        <p class="m-0 ml-3"><small><i class="fas fa-heart fa-fw"></i> <%= post.favorites.count %></small></p>
        <p class="m-0 ml-3"><small><i class="far fa-comment fa-fw"></i> <%= post.comments.count %></small></p>
      </div>
    </li>
  <% end %>
</ul>
<div class="toppage">
  <div class="toppage-post">
    <div class="toppage-top">
      <h5>ランキング</h5>
      <%= link_to 'もっと見る', ranking_path %>
    </div>
    <%= render 'posts/posts', posts: @posts %>
  </div>
  <div class="toppage-user">
    <div class="toppage-top">
      <h5>おすすめユーザー</h5>
      <%= link_to 'もっと見る', users_path %>
    </div>
    <%= render 'users/users', users: @users %>
  </div>
</div>