config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    member do
      get :timeline
    end
  end
  
  get 'ranking', to: 'posts#ranking'
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 3000 }
  validates :title, presence: true, length: { maximum: 50 }
  
  def self.search(search)
    if search
      Post.where(['title LIKE ?', "%#{search}%"])
    else
      Post.all
    end
  end
  
  has_many :reverses_of_favorite, class_name: 'Favorite'
  has_many :likers, through: :reverses_of_favorite, source: :user, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :like_users, through: :favorites, source: :user
  
  has_many :comments, dependent: :destroy
  
  mount_uploader :image, ImageUploader
  
  is_impressionable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in, only: [:new]
  before_action :correct_user, only: [:edit, :update, :destroy]
  impressionist :actions=> [:show]
  
  def index
    @posts = Post.order(id: :desc).page(params[:page]).per(10).search(params[:search])
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order(id: :desc)
    @comment = Comment.new
    @likes_count = Favorite.where(post_id: @post.id).count
    @comments_count = Comment.where(post_id: @post.id).count
    impressionist(@post, nil, unique: [:session_hash])
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '記事を投稿しました。'
      redirect_to root_url
    else
      @posts = current_user.posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = '記事の投稿に失敗しました。'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    if @post.update(post_params)
      flash[:success] = '更新しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end


  def destroy
    @deleted_post_id = @post.id
    @post.destroy
  end
  
  def timeline
    @user = current_user
    @posts = @user.feed_posts.order(id: :desc).page(params[:page]).per(100)
  end
  
  def ranking
    @posts = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(100).pluck(:post_id))
  end
  

  private

  def post_params
    params.require(:post).permit(:title, :content, :image, :remove_image)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post && logged_in?
      redirect_to root_url
    end
  end
end

app/views/posts/_index_items.html.erb
<ul class="nav nav-tabs nav-justified" id="user_items">
  <li class="nav-item"><a href="<%= posts_path %>" class="nav-link <%= 'active' if current_page?(posts_path) %>">新着投稿</a></li>
  <% if logged_in? %>
    <li class="nav-item"><a href="<%= timeline_post_path(current_user) %>" class="nav-link <%= 'active' if current_page?(timeline_post_path(current_user)) %>">タイムライン</a></li>
  <% end %>
  <li class="nav-item"><a href="<%= ranking_path %>" class="nav-link <%= 'active' if current_page?(ranking_path) %>">ランキング</a></li>
</ul>

app/views/posts/_likes.html.erb
<ul class="list-unstyled">
  <% posts.each do |post| %>
  <li class="card" id="post-<%= post.id %>">
    <!--<%= post.inspect %>-->
    <div class="card-body p-2">
      <div class="d-flex justify-content-around">
        <h5 class="card-title mb-1"><%=post.title %></h5>
        
        <%= render 'favorites/favorite_button', post: post %>
        
      </div>
      <p class="card-text m-0">投稿者：<%= link_to post.user.name, user_path(post.user) %></p>
      <p class="card-text m-0"><small class="text-muted">カテゴリー：<%=post.category %></small></p>
      <p class="card-text"><small class="text-muted">投稿日時：<%= post.created_at %></small></p>
    </div>
    <%= render 'posts/posts_button', post: post %>
  </li>
  <% end %>
  <%= paginate posts %>
</ul>

<script> 
$('.card').on('click', function(event) {
  const id = $(this).attr("id").replace("post-", "");
  if (event.target.tagName !== 'svg' && event.target.tagName !== 'A' && event.target.tagName !== 'path') {
    location.href = "/posts/" + id;
  }
})
</script> 

app/views/posts/_post_format.html.erb
<div class="post_show p-2">
  <%= form_with(model: @post, local: true) do |f| %>
    <div class="form-group">
      <div class="pb-5">
        <%= f.label :title, "タイトル" %> <span class="badge badge-danger">必須</span>
        <%= f.text_field :title, placeholder: "タイトルを入力(50文字以内)", class: 'form-control' %>
      </div>
      <%=f.label :image,"サムネイル画像（選択しない場合、現在の画像が表示されます。）" %>
      <div class="post-image pb-5">
        <div class="trim-post-image-lg pb-2">
          <img id="aavatar_img_prev" src="#" class="hidden">
          <% if @post.image? %>
            <%= image_tag @post.image.url, class: 'aavatar_present_img' %>
          <% elsif %>
            <%= image_tag ('/no_post_image.png'), class: 'aavatar_present_img' %>
          <% end %>
        </div>
        <div>
          <p><%= f.file_field :image, id: 'apost_img' %></p>
          <p><%= f.check_box :remove_image %>画像を削除する</p>
        </div>
      </div>
      <div>
        <%= f.label :content, "本文" %> <span class="badge badge-danger">必須</span>
        <%= f.text_area :content, placeholder: "本文を入力(3000文字以内)", class: 'form-control', rows: 20 %>
      </div>
    </div>
    <div class="button-set">
      <%= link_to "キャンセル", :back, class: 'cancel-button'%>
      <%= f.submit '投稿する', class: 'submit-button' %>
    </div>
  <% end %>
</div>

app/views/posts/_post_image.html.erb
<% if post.image? %>
  <%= image_tag post.image.url %>
<% elsif %>
  <%= image_tag ('/no_post_image.png') %>
<% end %>

app/views/posts/_posts.html.erb
<ul class="list-unstyled skill-list jscroll">
  <% posts.each_with_index do |post, index| %>
  <li class="post-index" id="post-<%= post.id %>">
    <div class="p-2">
      <div class="d-flex">
        <div class="favorite_button_position_parent">
          <div class="trim-post-image m-0">
            <%= render 'posts/post_image', post: post %>
          </div>
          <% if controller.controller_name == 'toppages' && controller.action_name == 'index' %>
          <div class="post-index-ranking">
            <span></span>
            <p><%= index+1 %></p>
            </div>
          <% end %>
          <div class="favorite_button_position_child">
            <%= render 'favorites/favorite_button', post: post %>
          </div>
        </div>
        <div class="pl-3 post-title">
          <h5><%=post.title %></h5>
          <div class="post-bottom">
            <p><small class="text-muted post_user_name"><i class="fas fa-user fa-fw"></i> <%= link_to post.user.name, user_path(post.user) %></small></p>
            <p><small class="text-muted"><i class="far fa-clock fa-fw"></i> <%= time_ago_in_words(post.created_at) %></small></p>
            <div class="d-flex justify-content-between">
              <div class="d-flex justify-content-between">
                <p class="m-0" data-toggle="tooltip" data-original-title="閲覧"  data-placement="bottom"><small class="text-muted"><i class="fas fa-eye fa-fw"></i> <%= post.impressionist_count %></small></p>
                <p class="m-0 ml-3" data-toggle="tooltip" data-original-title="お気に入り"  data-placement="bottom"><small class="text-muted"><i class="fas fa-heart fa-fw"></i> <%= post.favorites.count %></small></p>
                <p class="m-0 ml-3" data-toggle="tooltip" data-original-title="コメント"  data-placement="bottom"><small class="text-muted"><i class="far fa-comment fa-fw"></i> <%= post.comments.count %></small></p>
              </div>
              <%= render 'posts/posts_button', post: post %>
            </div>
          </div>
         </div>
      </div>
    </div>
    <hr class="m-0">
  </li>
  <% end %>
</ul>

app/views/posts/_posts_button.html.erb
<% if current_user == post.user %>
  <!--編集ボタン-->
  <div class="d-flex justify-content-end">
    <div class="mt-1" data-toggle="tooltip" data-original-title="編集" data-placement="bottom">
      <%=link_to edit_post_path(post), class: "btn btn-default post-edit-button" do %>
        <i class="far fa-edit"></i>
      <% end %>
    </div>
    <!--削除ボタン-->
    <div id="deleted_button" class="mt-1" data-toggle="tooltip" data-original-title="削除" data-placement="bottom">
      <%= link_to post, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-default post-delete-button", remote: true do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/_search.html.erb
<%= form_tag(posts_path, :method => 'get') do %>
  <div class="d-flex justify-content-center">
    <%= text_field_tag :search, '', class: 'title-search form-control', :placeholder => "タイトル検索"%>
    <%= button_tag :type => "submit", :class =>"searth-btn btn btn-default btn-dark" do %>
      <i class="fa fa-search"></i>
    <% end %>
  </div>
<% end %>

app/views/posts/destroy.js.erb
$("#post-<%= @deleted_post_id %>").fadeOut('fast');
var count = $('#past-post-count').text();
$('#past-post-count').text(String(parseInt(count)-1));

app/views/posts/edit.html.erb
<%= render 'posts/post_format' %>

app/views/posts/index.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="pb-5">
      <%= render 'posts/search' %>
    </div>
    <div>
      <%= render 'posts/index_items' %>
    </div>
    <div>
      <% if @posts.count > 0  %>
        <%= render 'posts/posts', posts: @posts %>
      <% else %>
        <p>該当する投稿が見つかりませんでした。</p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'posts/post_format' %>

app/views/posts/ranking.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="pb-5">
      <%= render 'posts/search' %>
    </div>
    <div>
      <%= render 'posts/index_items' %>
    </div>
    <div>
      <% if @posts.count > 0  %>
        <%= render 'posts/posts', posts: @posts %>
      <% else %>
        <p>該当する投稿が見つかりませんでした。</p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post_show p-2">
  <div class="d-flex">
    <%= render 'users/user_image', user: @post.user %>
    <div class="pl-3 post-title">
      <p class="m-0">投稿者：<%= link_to @post.user.name, user_path(@post.user) %></p>
      <p class="m-0">投稿日：<%= @post.created_at.in_time_zone("Tokyo").strftime("%Y/%m/%d %H:%M") %>・<%= time_ago_in_words(@post.created_at) %></p>
      <div class="d-flex justify-content-first">
        <p class="m-0" data-toggle="tooltip" data-original-title="閲覧"  data-placement="bottom"><i class="fas fa-eye fa-fw"></i> <%= @post.impressionist_count %></p>
        <p class="m-0 ml-3" data-toggle="tooltip" data-original-title="お気に入り"  data-placement="bottom"><i class="fas fa-heart fa-fw"></i> <%= @post.favorites.count %></p>
        <p class="m-0 ml-3" data-toggle="tooltip" data-original-title="コメント"  data-placement="bottom"><i class="far fa-comment fa-fw"></i> <%= @post.comments.count %></p>
      </div>
    </div>
  </div>
  <%= render 'posts/posts_button', post: @post %>
  <div class="post-show-title-favorite d-flex justify-content-between">
    <h2><%=@post.title %></h2>
    <%= render 'favorites/favorite_button', post: @post %>
  </div>
  <div class="post-show">
    <div class="trim-post-image-lg">
      <%= render 'posts/post_image', post: @post %>
    </div>
  </div>
  <div class="post-show-content"><%= safe_join(@post.content.split("\n"), tag(:br)) %></div>
  <hr>
  <%= render 'comments/form', post: @post, comment: @comment %>
  <%= render 'comments/index', comments: @comments %>
</div>

app/views/posts/timeline.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="pt-3 pb-3 mt-3 mb-3">
      <ul class="nav nav-tabs nav-justified" id="user_items">
        <li class="nav-item"><a href="<%= posts_path %>" class="nav-link <%= 'active' if current_page?(posts_path) %>">新着投稿</a></li>
        <li class="nav-item"><a href="<%= timeline_post_path(current_user) %>" class="nav-link <%= 'active' if current_page?(timeline_post_path(current_user)) %>">タイムライン</a></li>
        <li class="nav-item"><a href="<%= new_user_path %>" class="nav-link <%= 'active' if current_page?(new_user_path) %>">タイムライン</a></li>
      </ul>
      <%= form_tag(posts_path, :method => 'get') do %>
        <div class="d-flex justify-content-center pt-4">
          <%= text_field_tag :search, '', class: 'title-search form-control', :placeholder => "タイトル検索"%>
          <%= button_tag :type => "submit", :class =>"btn btn-default btn-dark" do %>
            <i class="fa fa-search"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div>
      <% if @posts.count > 0  %>
        <%= render 'posts/posts', posts: @posts %>
      <% else %>
        <p>該当する投稿が見つかりませんでした。</p>
      <% end %>
    </div>
  </div>
</div>