config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    member do
      get :timeline
    end
  end
  
  get 'ranking', to: 'posts#ranking'
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="flash_messages fixed-top row justify-content-center">
  <div class="flash_message col-md-6">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer mt-5">
  <div class="title-logo">
    <a class="navbar-brand" href="/">minimaLife</a>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="sticky-top">
  <ul class="menu d-flex justify-content-between">
    <li class="title-logo mr-auto"><a href="/">minimaLife</a></li>
    <% if logged_in? %>
      <li class="navbar-item navbar-new-post" data-toggle="tooltip" data-original-title="記事作成" data-placement="bottom">
        <%=link_to new_post_path do %>
          <i class="fas fa-pen fa-lg"></i>
        <% end %>
      </li>
      <li class="navbar-item navbar-icon">
        <a class="init-bottom">
          <div class="trim-image-to-circle-navbar m-0">
            <% if current_user.image? %>
              <%= image_tag current_user.image.url %>
            <% elsif %>
              <%= image_tag ('/no_user_image.png') %>
            <% end %>
          </div>
        </a>
        <ul class="menu__second-level">
          <li><%= link_to 'マイページ', user_path(current_user) %></li>
          <li class="dropdown-divider m-0"></li>
          <li><%= link_to 'ユーザー情報編集', edit_user_path(current_user) %></li>
          <li class="dropdown-divider m-0"></li>
          <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
        </ul>
      </li>
    <% elsif %>
      <li class="navbar-item" data-toggle="tooltip" data-original-title="新規登録" data-placement="bottom">
        <%=link_to signup_path do %>
          <i class="fas fa-user-plus fa-lg"></i>
        <% end %>
      </li>
      <li class="navbar-item" data-toggle="tooltip" data-original-title="ログイン" data-placement="bottom">
        <%=link_to login_path do %>
          <i class="fas fa-sign-in-alt fa-lg"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Microposts</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto"></ul>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <li class="nav-item"><%= link_to '新規投稿', new_post_path, class: 'nav-link' %></li>
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>minimaLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script> 
      $('.post-index').on('click', function(event) {
        const id = $(this).attr("id").replace("post-", "");
        if (event.target.tagName !== 'svg' && event.target.tagName !== 'A' && event.target.tagName !== 'path') {
          location.href = "/posts/" + id;
        }
      })

      $('.favorite_button').click(function (event) {
        event.stopPropagation();
      });
      
      
      $('.media').on('click', function(event) {
        const id = $(this).attr("id").replace("user-", "");
          location.href = "/users/" + id;
      })
      
      $('.follow_button').click(function (event) {
        event.stopPropagation();
      });
      
      $( document ).on('turbolinks:load', function() {
        function readURL(input) {
          if (input.files && input.files[0]) {
            var reader = new FileReader();
       
            reader.onload = function (e) {
              $('#aavatar_img_prev').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
          }
        }
       
        $("#apost_img").change(function(){
          $('#aavatar_img_prev').removeClass('hidden');
          $('.aavatar_present_img').remove();
          readURL(this);
        });
      });
      
      $(function(){
      	$('.unfollow').hover(function(){
      		$(this).text('フォロー解除');
      		$(this).css('color', 'red');
      	},function(){
      		$(this).text('フォロー中');
      		$(this).css('color', 'white');
      	});
      });
      
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
      
      $( document ).on('turbolinks:load', function() {
        function readURL(input) {
          if (input.files && input.files[0]) {
            var reader = new FileReader();
       
            reader.onload = function (e) {
              $('#avatar_img_prev').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
          }
        }
       
        $("#post_img").change(function(){
          $('#avatar_img_prev').removeClass('hidden');
          $('.avatar_present_img').remove();
          readURL(this);
        });
      });
      
      setTimeout(function(){
        $('.flash_messages').fadeOut('slow');
      }, 2000)
    </script> 
    
  </body>
</html>